### ISSUE TITLE
Format scraped data properly before sending it to the user.

### ISSUE THREAD

**Issue by dmorand** [dialoguemd/covidflow#13]
Data may contain HTML tags for example. We should be able to convert some into the markdown format supported by the Chat Widget.

**Comment by vlavoie** [comment]
I made a branch for this but I think it might be better to not do this since markdown supports HTML tags. I will investigate further to see what botfront allows.

**Comment by fparga** [comment]
Keep in mind that a lot of the botfront default styling is overridden in covid-19, we might have to alter the CSS to make it render properly in the webapp.

See: https://github.com/dialoguemd/covid-19/blob/master/src/components/rasa-chatbot.tsx

**Comment by vlavoie** [comment]
After some testing I can definitely confirm that HTML tags are not supported anyways
