### ISSUE TITLE
In daily CI, return from Q&A should not offer assessment

### ISSUE THREAD

**Issue by lthibau** [dialoguemd/covidflow#152]
In the daily CI flow, when coming back from Q&A, the option to do the self-assessment is offered and it should not. This means that we must assign self-assess-done=true before going to the enrollment, and keep that variable set in the profile.

**Comment by NetBKarine** [comment]
This might have been solved by https://github.com/dialoguemd/covidflow/pull/182

**Comment by lthibau** [comment]
I haven't observed this in latest version
