### ISSUE TITLE
We need to block the text field after the goodbye message

### ISSUE THREAD

**Issue by lthibau** [dialoguemd/covidflow#159]
Otherwise we can enter text and nothing happens.

**Comment by fparga** [comment]
Like discussed we should decide what to do at the end of the conversation. Staying on the page where user can do nothing is maybe not the best UX.

We could maybe have a pop-up message with buttons to redirect the user somewhere, telling him he can now close this page, or something.

**Comment by fparga** [comment]
Blocked by #225
