### ISSUE TITLE
Flow: critical symptoms in Daily CI flow incorrect

### ISSUE THREAD

**Issue by lthibau** [dialoguemd/covidflow#185]
If the user feels worse and answers "yes" to:
Are you experiencing any of the following symptoms:
- Severe difficulty breathing
- Severe chest pain
- Having a hard time waking up
- Feeling confused
- Losing consciousness

Then they should see:
These symptoms require immediate response, so please call 911 immediately, or go to your nearest emergency department.

And the flow ends there.

Currently, it continues to the Keep or cancel CI page, that's incorrect.

**Comment by NetBKarine** [comment]
After discussion with Linda, it was established that the reminder should be removed, since the person should be taken care of by medical experts and the check-in becomes useless
