### ISSUE TITLE
In Daily CI, need to add "still"/"encore" to fever and cough questions

### ISSUE THREAD

**Issue by lthibau** [dialoguemd/covidflow#204]
For has-fever and has-cough conditions, prompts should say "still" or "encore" when asking the question. I don't see this behavior for the Kim profile: https://docs.google.com/spreadsheets/d/1-Yetc6AmAZBpOGqiVfBrGsnt8ODl4CsTGjwV0jI_YXI/edit#gid=0

**Comment by fparga** [comment]
Too much work and added complexity for what seems like a small detail. Our time will be better spent on something else.

@lthibau don't hesitate to reopen if you disagree
