### ISSUE TITLE
In Daily CI flow, change one link at the end

### ISSUE THREAD

**Issue by lthibau** [dialoguemd/covidflow#231]
In the Recommendations page, change the first link (that goes to Dialogue) for this one:

EN
https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19.html

FR:
https://www.canada.ca/fr/sante-publique/services/maladies/maladie-coronavirus-covid-19.html

**Comment by lthibau** [comment]
For condition ageOver65==true | preconditions==true?, two links will go to canada.ca, but they are different - we should have different labels
EN:
For https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19.html, use label [canada.ca/general]
For https://www.canada.ca/en/public-health/services/publications/diseases-conditions/vulnerable-populations-covid-19.html, use label [canada.ca/vulnerable-populations]

FR:
For https://www.canada.ca/fr/sante-publique/services/maladies/maladie-coronavirus-covid-19.html, use label [canada.ca/general]
For https://www.canada.ca/fr/sante-publique/services/publications/maladies-et-affections/populations-vulnerables-covid-19.html, use label [canada.ca/populations-vulnerables]

**Comment by NetBKarine** [comment]
The first part is replaced by #256, but the second part on canada.ca link will be done
