### ISSUE TITLE
In Daily CI, page Feel worse, 811 link not by province

### ISSUE THREAD

**Issue by lthibau** [dialoguemd/covidflow#233]
Profile Mike has ca-on as a province, but in the following message, the number shows up as 811 and it should be 1-866-797-0000

You may want to discuss your situation with your doctor, if that’s possible, or call [811]

This should be validated for all provinces and all [811] instances

**Comment by NetBKarine** [comment]
The message mentionned has the good logic, but there is one in feel better that doesn't (utter_daily_ci__feel_better__breathing_difficulty_recommendation_1). This problem is probably a consequence of #237

**Comment by mathieubergeron** [comment]
seems to be fixed by #237 
![image](https://user-images.githubusercontent.com/5585923/81977731-7c6a7100-95f8-11ea-8f8e-5add168e261d.png)
