### ISSUE TITLE
Handle daily CI with invalid ID

### ISSUE THREAD

**Issue by fparga** [dialoguemd/covidflow#258]
Right now if someone goes to the daily CI URL with an invalid ID (e.g. https://covid19.dialogue.co/#/rasa/ci/foo) the dialogue starts like everything is OK, saying Hello None and asking if the person wants to cancel its daily reminder.

We should handle the situation differently. We could for example say something like the link seems to be invalid and asking the user if he wants to be redirected to the self assessment. Alternatively we might try to recover by asking more information to the user to see if he is registered to the daily CI.

Ask @lthibau for input on what would be the best way to handle the situation.

**Comment by mathieubergeron** [comment]
The error that is logged is also not very useful (`Tuple index out of range`):

https://app.datadoghq.com/logs?cols=host%2Cservice%2Cstatus%2C%40sender_id&event=AQAAAXItjpeT0wZTsgAAAABBWEl0anBlYXVOTUUwSzRRSU1BQQ&from_ts=1589900478258&index=&live=true&messageDisplay=inline&query=env%3Aprod-ca++++%28app%3Acovidflow+OR+job%3Asend-daily-reminders%29&stream_sort=desc&to_ts=1589904078258

**Comment by lthibau** [comment]
I added a proposal in the flow: https://drive.google.com/open?id=1ECq5_FITxtKP5UqiyNU2RJxEb0owz6QV

There is a new page that will precede the Entry page
