### ISSUE TITLE
Fix env variable use in integration tests library

### ISSUE THREAD

**Issue by fparga** [dialoguemd/covidflow#262]
See if we can do a quick fix to allow env variables use in our integration tests. I know it's not ideal right now since we haven't yet mirrored the project, set up the pipeline, etc. But this fix is necessary to run our tests so let's do it manually this time.

**Comment by vlavoie** [comment]
I'll make a fix based off @LaurenceDupont's branch and release on pypi on a temporary token.

**Comment by vlavoie** [comment]
This was fixed and pushed to rasa-integration-testing 0.1.3
