### ISSUE TITLE
Duplicated file: setup_structlog.py

### ISSUE THREAD

**Issue by mathieubergeron** [dialoguemd/covidflow#264]
As we needed to fix the log formatting ASAP, we allowed ourselves to duplicate the `setup_structlog.py` file within the `core` and `action-server` projects. This was temporary and we should find a way to reuse the same file in both projects.

related PR: https://github.com/dialoguemd/covidflow/pull/261

**Comment by fparga** [comment]
Properly fixing this would require either having another project in the repo (like a shared library) or extracting the common code as an external dependency. Since dialogue already has a logging library I don't think it's necessary to spend time on this.
