### ISSUE TITLE
Make Rasa core debug mode configurable using an environment variable.

### ISSUE THREAD

**Issue by dmorand** [dialoguemd/covidflow#31]
We currently start the Rasa core applications using the `--debug` flag (in our Dockerfile) which generates a lot of noise that is not parseable by the Datadog log engine.

We should make this configurable using an environment variable (or maybe simply change the endpoint when running them in our docker-compose.yml).

**Comment by mathieubergeron** [comment]
Ça aurait été l'fun de simplement pouvoir faire 
> docker run rasa --debug
mais ce n'est pas possible d'ajouter des parametres à la commande par défaut.

Donc on pourrait:
1. Simplement enlever le --debug de la commande par défaut. À ce moment, si on veut ajouter --debug,  il faudrait redéfinir la command en entier (incluant --cors, --port, etc).

2. Ajouter une variable d'environnement et changer notre entrypoint pour qu'il ressemble à ça:
```
ENV FLAGS=
ENTRYPOINT exec rasa run --port 8080 --enable-api --cors "*" $FLAGS
```
Donc après on peut passer une variable d'environnement:
> docker run -e FLAGS="--debug" rasa

Qu'est-ce qu'on préfère..? Est-ce qu'il y a une alternative qui m'échappe?

**Comment by fparga** [comment]
Rien de tout ça, rasa supporte de spécifier le log level via la variable d'environnement `LOG_LEVEL=DEBUG`

**Comment by fparga** [comment]
Y a DEBUG, INFO, WARN et ERROR de possible. Le défaut est INFO.

**Comment by mathieubergeron** [comment]
ah bin super! J'avais pas pensé regardé. Merci!
