### ISSUE TITLE
Change rasasdk Action and QuestionAnsweringProtocol to run async

### ISSUE THREAD

**Issue by vlavoie** [dialoguemd/covidflow#34]
Current implementation of these are run synchronized which will affect their responsiveness when performing slow operations such as http requests.

For the rasasdk, we could reuse the async objects from beautiful-mind.

**Comment by dmorand** [comment]
This might be unnecessary since Rasa SDK Actions are now "natively" async in the version we use (1.9.0)

**Comment by dmorand** [comment]
We must ensure that Q&A services requests are performed asynchronously to avoid blocking Rasa event loop.

We must also validate if we need to respecify the `async` keyword when overriding async functions from Action and FormAction.
