### ISSUE TITLE
Ensure the whole application is HA compliant.

### ISSUE THREAD

**Issue by dmorand** [dialoguemd/covidflow#40]
Some Rasa features (like reminders which are stored in a specific instance) are not HA compliant. We must ensure that our application scales (both up and down) properly and that we don't have issues when a node goes down.

We might also have issues with Websockets.

nginx.ingress.kubernetes.io/session-cookie-change-on-failure and DB tracker store are steps in the right direction.

**Comment by fparga** [comment]
Tests we performed to this date makes us confident enough in the HA of the application
