### ISSUE TITLE
Action Server unit tests can't run in CI

### ISSUE THREAD

**Issue by dmorand** [dialoguemd/covidflow#43]
Any test that depends on rasa-sdk will fail in the CI.

This seems caused by the fact that we don't install rasa-sdk. We should probably add it in our dev dependencies instead of installing it in a separate target.

**Comment by fparga** [comment]
This should be solved by #1

**Comment by vlavoie** [comment]
Is this still an issue after #1 ?

**Comment by fparga** [comment]
@LaurenceDupont @NetBKarine ?

**Comment by NetBKarine** [comment]
Was effectively solved by #1
